### ISSUE TITLE
[GENERAL] Using an integer unique key for BatchFiles

### ISSUE THREAD

**Issue by devilicecream** [immuni-app/immuni-backend-common#17]
I'd like to thank you guys first for all the work you put into this, you're definitely not getting enough credit for it.

The issue I'd like to point out is with the schema of the `BatchFile` documents: I see that you're using a field called `index` to uniquely identify and index the batches generated from the user's keys uploads.

However, using unique integer indexes in MongoDB is a common bad practice, especially for collections with a large amount of documents, as it's pointed out in the MongoDB 3.* documentation: https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field/#considerations
I'm not sure why this page is not included in the MongoDB 4 documentation as well (I think they just removed the tutorials section from it) but the considerations made there are just as valid for MongoDB 4 as they were for v3.

Is there any reason why an integer field was preferred instead of the [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) already indexed, unique and incremental by design in `BatchFile._id`?

Additionally, is there any reason why the increment of the `index` field is implemented as below, instead of using one of the suggested strategies to create an auto incrementing unique field, as described in the documentation page already linked [above](https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field/)?

from [immuni-backend-exposure-ingestion/tasks/process_uploads.py#L101-L110](https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/d589a4263c7d55d9020e8362b61cdd9825e9ed18/immuni_exposure_ingestion/tasks/process_uploads.py#L101-L110):
```python
            index = last_index + 1


            batch_file = BatchFile(
                index=index,
                keys=keys,
                period_start=period_start,
                period_end=period_end,
                sub_batch_index=1,
                sub_batch_count=1,
            )
```
This approach is clearly flawed as it does not allow batch generation to be performed concurrently (hence the shared lock acquired before doing this).

By using an ObjectId, or even just a smarter solution to achieve auto increment, you could easily start processing batches concurrently instead, making better use of celery and reducing the processing time of batches, that would otherwise grow linearly with the number of users of the app. Of course that is after taking on the other concurrency issues pointed out in [immuni-backend-exposure-ingestion#15](https://github.com/immuni-app/immuni-backend-exposure-ingestion/issues/15)

I would be happy to help if you need clarification or an additional pair of hands to dive into this issues.

Thank you again!

**Comment by xelhark** [comment]
Hello @devilicecream !

First of all I’d like to thank you for taking the time to write this. We really appreciate it 😄 

Let’s address your concerns one by one:

> using unique integer indexes in MongoDB is a common bad practice, especially for collections with a large amount of documents

I agree, it’s not a good practice to have unique integer indexes, but there are a couple of reasons why we think it is acceptable in this context:
1) The collection will never contain many documents. The system will only create a handful of documents per day (1~4 at most) and we will only store the documents created in the last 14 days. This means that the collection will contain roughly 50 documents at any given time. With that said, I think we can agree that performance issues are out of discussion.
2) Integer identifiers are consecutive, and therefore, urls for Batches can be calculated client side, given the first and the last batch. This means that after requesting the info at the /v1/keys/index endpoint, clients can calculate locally which batch files they still have to download. This greatly simplifies the client logic.
3) If the ids were ObjectIDs, we would have to communicate the whole list in /v1/key/index, the client logic would be a bit more complex (it would have to exclude all batch files that were already downloaded from the given list) and the amount of data communicated in this step would be much bigger (4-5 times roughly), which considering the amount of requests, would also have a repercussion on to the CDN costs.


>Additionally, is there any reason why the increment of the index field is implemented as below, instead of using one of the suggested strategies to create an auto incrementing unique field, as described in the documentation page already linked above?

This is a valid point, but considering that there is no concurrency issue (the task is executed a couple of times per day and there is also a lock preventing concurrent executions), we figured it would be more explicit to read that logic in the code rather than hide it into a database configuration. If the task was susceptible to concurrency issues I agree that your proposal would be a much better solution. This is more of a readability compromise we thought was fair.

**Comment by devilicecream** [comment]
Hi @earien and @xelhark ! Thank you for your reply and sorry for the delay with my response.

I see that the context justifies this choice in this case, and there should not be any direct disadvantages to this implementation for now.

I would just like to point out that this approach will not be flexible in case of future changes where other parts of the project might want to write to the batches collection for some reason, since the increment code is in this repo, but the `BatchFile` model is available in the common repo. 

I think it is indeed an acceptable compromise for now, but it might become a problem in the future.

Thank you for the explanation on how the mobile sdk works! You can close this or maybe attach it to a "tech debt" tag or something similar :)

**Comment by ocardia** [comment]
Hey @devilicecream, we are glad you are aligned in thinking the current solution is an acceptable pragmatic compromise.

Given the current status of the project, which does not envision any major change that would turn the potential issue you pointed out into an actual one, we are marking this issue as “enhancement” and “won’t fix”, thus closing it.
